# Generated by Django 5.1.4 on 2026-06-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CooperativeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ГСК «Камовец»', max_length=200, verbose_name='Название')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание (для главной)')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('established_year', models.CharField(blank=True, max_length=10, verbose_name='Год основания')),
                ('total_garages', models.CharField(blank=True, max_length=50, verbose_name='Количество гаражей')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Информация о кооперативе',
                'verbose_name_plural': 'Информация о кооперативе',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('category', models.CharField(choices=[('charter', 'Устав и учредительные документы'), ('protocol', 'Протоколы собраний'), ('regulation', 'Положения и правила'), ('other', 'Прочие документы')], default='other', max_length=50, verbose_name='Категория')),
                ('url', models.URLField(verbose_name='Ссылка на документ (Яндекс.Диск или другое)')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('period', models.CharField(max_length=100, verbose_name='Период')),
                ('content', models.TextField(verbose_name='Содержание отчёта (статьи доходов и расходов)')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на полный документ (Яндекс.Диск)')),
                ('date', models.DateField(verbose_name='Дата отчёта')),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Доходы (руб.)')),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Расходы (руб.)')),
            ],
            options={
                'verbose_name': 'Финансовый отчёт',
                'verbose_name_plural': 'Финансовые отчёты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetings_schedule', models.TextField(verbose_name='Расписание собраний')),
                ('fee_amount', models.CharField(max_length=100, verbose_name='Размер членского взноса')),
                ('fee_period', models.CharField(max_length=100, verbose_name='Периодичность оплаты')),
                ('fee_payment_info', models.TextField(verbose_name='Как и где платить взносы')),
                ('extra_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Важная информация',
                'verbose_name_plural': 'Важная информация',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('period', models.CharField(max_length=100, verbose_name='Период (напр. «2024 год» или «Лето 2024»)')),
                ('content', models.TextField(verbose_name='Описание выполненных работ')),
                ('date', models.DateField(verbose_name='Дата отчёта')),
            ],
            options={
                'verbose_name': 'Отчёт о работах',
                'verbose_name_plural': 'Отчёты о работах',
                'ordering': ['-date'],
            },
        ),
    ]
